export const routes = {
  home: `/`,
  logIn: `/logIn`,
  signUp: `/signUp`,
  forgotPassword: `/forgotPassword`,
  resetPassword: `/resetPassword`,
  updateEmail: `/updateEmail`,
  category: `/category`,
  destination: `/destination`,
  newDestination: `/newDestination`,
  termsOfUse: `/termsOfUse`,
  aboutUs: `/aboutUs`,
  contact: `/contact`,
  allUsers: `/allUsers`,
  user: `/user`,
};
